include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    unnecessary_new: true
    prefer_const_literals_to_create_immutables: true
    prefer_relative_imports: false
    always_use_package_imports: true
