name: almabike_shared
description: "Almabike shared project"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # service
  intl: any
  provider: ^6.1.2
  flutter_bloc: ^9.0.0
  latlong2: ^0.9.1

  retrofit: ^4.4.2
  dio: ^5.8.0+1
  logger: ^2.5.0
  json_annotation: ^4.9.0

  # native
  flutter_map: ^8.0.0
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18

  # utils
  flutter_gen: ^5.9.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  pretty_dio_logger: ^1.4.0

  # ui
  figma_squircle:
    git:
      url: https://github.com/Ax0elz/figma_squircle
      ref: 5f1ad5aaccdf31fc398fc141979ea845a0f45383
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.1

  # navigation
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ">=8.0.0 <10.0.0"
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_gen_runner: ^5.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/images/markers/
    - assets/images/media/
  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-VariableFont_wght.ttf
    - family: Icons
      fonts:
        - asset: assets/icons/Icons.ttf

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/gen/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: false
