name: almabike

packages:
  - apps/**

scripts:
  clean:
    exec: flutter clean
  build:
    run: fvm flutter pub run build_runner build --delete-conflicting-outputs --fail-on-severe
    exec:
      failFast: true
      concurrency: 1
  watch:
    run: fvm flutter pub run build_runner watch --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 1
  get:
    exec: flutter pub get
  fluttergen:
    exec: fluttergen
  gen_l10n:
    exec: flutter gen-l10n
  auto_fix:
    exec: flutter fix --apply

  upgrade_dependencies:
    exec: flutter pub upgrade --major-versions
  pod_install:
    exec: |
      cd ios && pod install && cd ..
