name: almabike_admin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  almabike_shared: 0.0.1+1
  auto_route: ^9.3.0+1
  provider: ^6.1.2
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3


dependency_overrides:
  almabike_shared:
    path: ../mobile-shared

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^9.3.0

flutter:
  uses-material-design: true
  generate: true
