name: mobility_hub_app
description: "Mobility Hub - Vehicle Sharing Platform"

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  auto_route: ^10.0.1
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3
  flutter_bloc: ^9.0.0
  mask_text_input_formatter: ^2.9.0
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.4
  mobile_scanner: ^6.0.10
  geolocator: ^13.0.3
  animated_custom_dropdown: ^3.1.1
  flutter_screenutil: ^5.9.3
  percent_indicator: ^4.2.5


  #Map
  dgis_mobile_sdk_map: ^12.6.3
  permission_handler: ^12.0.0+1

  freezed: ^2.5.8
  freezed_annotation: ^2.4.4

  mobility_hub_shared:
    path: ../mobile-shared


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15


flutter_native_splash:
  color: "#849D65"
  color_dark: "#849D65"
  android_12:
    color: "#849D65"
    color_dark: "#849D65"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/dgissdk.key
