name: almabike_app
description: "Almabike app project"

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  almabike_shared: 0.0.1+1
  auto_route: ^9.3.0+1
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.0.0
  mask_text_input_formatter: ^2.9.0

dependency_overrides:
  almabike_shared:
    path: ../mobile-shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.3.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
